import Head from "next/head";
import Image from "next/image";
import PokemonList from "@/components/pokemonList";
import { useState, useEffect } from "react";
import styles from "@/styles/Homepage.module.scss";

export default function Home() {
  const [classicPokemonList, setClassicPokemonList] = useState([]);
  const [newPokemonList, setNewPokemonList] = useState([]);

  useEffect(() => {
    fetch("https://pokeapi.co/api/v2/pokemon/?limit=9")
      .then((res) => res.json())
      .then((data) => setClassicPokemonList(data.results));

    fetch("https://pokeapi.co/api/v2/pokemon/?limit=9&offset=151")
      .then((res) => res.json())
      .then((data) => setNewPokemonList(data.results));
  }, []);

  return (
    <>
      <Head>
        <title>Pokedex by Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Homepage}>
        <h1>My Pokedex</h1>
        <PokemonList title="I classici" pokemonList={classicPokemonList} />
        <PokemonList
          title="Una nuova generazione"
          pokemonList={newPokemonList}
        />
      </div>
    </>
  );
}
